import type { Difficulty, WordEntry } from '../../src/shared/types';

/*
 * English word pack (spec §12): curated, no player prompts. Each entry is
 * "word|alias|alias" — aliases are other names that also count as correct.
 * Rules (enforced by tests): ≥ 300 words of ≥ 3 letters, no duplicates,
 * every word and alias passes the chat moderator; no brands, religious,
 * political or national symbols, weapons, alcohol or smoking.
 */

const EASY = [
  'sun',
  'moon',
  'star',
  'house|home',
  'tree',
  'flower',
  'fish',
  'cat|kitten',
  'dog|puppy',
  'apple',
  'banana',
  'car',
  'boat',
  'kite',
  'umbrella',
  'cloud',
  'rain',
  'heart',
  'ball',
  'balloon',
  'cup|mug',
  'book',
  'clock',
  'key',
  'ladder',
  'snowman',
  'spider',
  'snake',
  'egg',
  'mountain|hill',
  'rainbow',
  'pencil',
  'glasses|spectacles',
  'cake',
  'lollipop',
  'mushroom',
  'tent',
  'door',
  'candle',
  'ice cream|icecream',
  'hat|cap',
  'shoe|shoes',
  'sock|socks',
  'shirt|tshirt|t-shirt',
  'bed',
  'chair',
  'table',
  'lamp',
  'phone|mobile|telephone',
  'cow',
  'duck',
  'frog',
  'bird',
  'bee',
  'ant',
  'owl',
  'pig',
  'horse',
  'sheep',
  'lion',
  'tiger',
  'monkey',
  'elephant',
  'mouse|rat',
  'rabbit|bunny',
  'turtle|tortoise',
  'whale',
  'crab',
  'bread',
  'cheese',
  'pizza',
  'burger',
  'orange',
  'grapes',
  'carrot',
  'tomato',
  'potato',
  'onion',
  'corn',
  'milk',
  'tea|chai',
  'rice',
  'bus',
  'train',
  'bicycle|cycle|bike',
  'aeroplane|airplane|plane',
  'rocket',
  'ship',
  'truck|lorry',
  'drum',
  'guitar',
  'bell',
  'box',
  'bag',
  'ring',
  'crown',
  'fire',
  'leaf',
  'grass',
  'sea|ocean',
  'window',
  'spoon',
  'fork',
  'plate',
  'bottle',
  'pen',
  'eraser|rubber',
  'ruler|scale',
  'scissors',
  'comb',
  'toothbrush',
  'soap',
  'towel',
  'bucket',
  'broom',
  'candy|sweet',
  'cookie|biscuit',
  'sandwich',
  'watermelon',
  'strawberry',
  'pineapple',
  'lemon',
  'mango',
  'coconut',
  'peacock',
  'parrot',
  'butterfly',
  'snail',
  'ladybug|ladybird',
  'dinosaur',
  'robot',
  'ghost',
  'sunflower',
  'cactus',
  'pumpkin',
  'nest',
  'worm',
];

const MEDIUM = [
  'bridge',
  'island',
  'river',
  'volcano',
  'desert',
  'waterfall',
  'lighthouse',
  'castle',
  'igloo',
  'windmill',
  'tractor',
  'helicopter',
  'submarine',
  'ambulance',
  'fire engine|fire truck',
  'scooter',
  'skateboard',
  'parachute',
  'hot air balloon',
  'traffic light|traffic signal',
  'bus stop',
  'school',
  'hospital',
  'library',
  'market',
  'garden',
  'farm',
  'playground',
  'swing',
  'slide',
  'seesaw',
  'football|soccer',
  'cricket',
  'badminton',
  'chess',
  'tennis',
  'basketball',
  'bat',
  'wicket|stumps',
  'goal',
  'trophy',
  'medal',
  'whistle',
  'camera',
  'television|tv',
  'computer|laptop',
  'keyboard',
  'headphones',
  'microphone|mic',
  'radio',
  'calculator',
  'battery',
  'magnet',
  'telescope',
  'microscope',
  'globe',
  'map',
  'compass',
  'backpack|schoolbag',
  'notebook',
  'crayon',
  'paintbrush|brush',
  'sharpener',
  'stapler',
  'envelope|letter',
  'stamp',
  'newspaper',
  'calendar',
  'hourglass|sand timer',
  'kettle|teapot',
  'frying pan|pan',
  'fridge|refrigerator',
  'fan|ceiling fan',
  'sofa|couch',
  'pillow',
  'blanket',
  'mirror',
  'toothpaste',
  'shower',
  'bathtub',
  'stairs|staircase',
  'fence',
  'gate',
  'postbox|mailbox',
  'chimney',
  'roof',
  'garage',
  'sandcastle',
  'beach',
  'palm tree|coconut tree',
  'forest|jungle',
  'snowflake',
  'lightning|thunder',
  'tornado',
  'comet',
  'planet',
  'astronaut',
  'alien',
  'satellite',
  'sunglasses',
  'necklace',
  'earrings',
  'watch|wristwatch',
  'wallet|purse',
  'belt',
  'gloves|glove',
  'scarf',
  'raincoat',
  'boots',
  'sweater|jumper',
  'pyjamas|pajamas',
  'samosa',
  'dosa',
  'idli',
  'jalebi',
  'roti|chapati',
  'noodles',
  'popcorn',
  'pancake',
  'donut|doughnut',
  'cupcake',
  'honey',
  'butter',
  'juice',
  'chocolate',
  'kangaroo',
  'giraffe',
  'zebra',
  'penguin',
  'camel',
  'crocodile|alligator',
  'octopus',
  'jellyfish',
  'starfish',
  'dolphin',
  'squirrel',
  'hedgehog',
  'swan',
  'flamingo',
  'ostrich',
  'polar bear',
  'panda',
  'koala',
  'spiderweb|cobweb|spider web',
  'beehive',
  'scarecrow',
  'mermaid',
  'unicorn',
  'dragon',
  'pirate',
  'king',
  'queen',
  'clown',
  'chef|cook',
  'doctor',
  'teacher',
  'farmer',
  'police officer|police',
  'firefighter',
  'pilot',
  'magician',
];

const HARD = [
  'roller coaster|rollercoaster',
  'giant wheel|ferris wheel',
  'merry-go-round|carousel',
  'treasure chest|treasure',
  'solar system',
  'black hole',
  'time machine',
  'traffic jam',
  'birthday party',
  'picnic',
  'sandstorm',
  'snowball',
  'tug of war',
  'hide and seek',
  'musical chairs',
  'homework',
  'exam|examination|test',
  'report card',
  'school bus',
  'lunch box|tiffin',
  'water bottle',
  'pencil box|pencil case',
  'blackboard|chalkboard',
  'chalk',
  'duster',
  'sports day',
  'auto rickshaw|autorickshaw|rickshaw|auto',
  'railway station|station',
  'metro|subway',
  'escalator',
  'lift|elevator',
  'washing machine',
  'vacuum cleaner',
  'sewing machine',
  'typewriter',
  'fireworks',
  'campfire',
  'sleeping bag',
  'treehouse|tree house',
  'hammock',
  'lantern',
  'kaleidoscope',
  'trampoline',
  'aquarium|fish tank',
  'museum',
  'zoo',
  'circus',
  'stadium',
  'airport',
  'harbour|harbor|port',
  'skyscraper',
  'pyramid',
  'cave',
  'glacier',
  'eclipse',
  'shooting star',
  'constellation',
  'sunrise',
  'sunset',
  'thunderstorm',
  'puddle',
  'footprints|footprint',
  'shadow',
  'reflection',
  'magnifying glass',
  'jigsaw puzzle|jigsaw|puzzle',
  'yo-yo|yoyo',
  'spinning top|top|lattu',
  'marbles',
  'hopscotch',
  'paper boat',
  'paper plane|paper aeroplane',
  'sandpit',
  'snakes and ladders',
  'carrom',
  'ludo',
  'skipping rope|jump rope',
  'tightrope',
  'unicycle',
  'stilts',
  'bubble|bubbles',
  'origami',
  'piggy bank',
  'treasure map',
  'mountain climber|climber',
  'scuba diver|diver',
  'lifeguard',
  'detective',
  'postman|postwoman',
];

function parse(lines: readonly string[], difficulty: Difficulty): WordEntry[] {
  return lines.map((line) => {
    const [word, ...aliases] = line.split('|');
    return { word: word as string, aliases, difficulty };
  });
}

export const WORD_PACK: readonly WordEntry[] = [
  ...parse(EASY, 'easy'),
  ...parse(MEDIUM, 'medium'),
  ...parse(HARD, 'hard'),
];
