/**
 * English labels for the category pack (ids in `src/shared/categories.ts`).
 * Every label must pass the chat moderator (tested). Translations add a
 * sibling folder with the same keys.
 */
export const CATEGORY_LABELS: Record<string, string> = {
  fruits: 'Fruits',
  animals: 'Animals',
  sports: 'Sports',
  'street-food': 'Street Food',
  vehicles: 'Vehicles',
  stationery: 'Stationery',
  sky: 'Sky',
  music: 'Music',
  toys: 'Childhood Toys',
  ocean: 'Ocean',
};

export const ITEM_LABELS: Record<string, string> = {
  mango: 'Mango',
  banana: 'Banana',
  apple: 'Apple',
  grapes: 'Grapes',
  lion: 'Lion',
  elephant: 'Elephant',
  monkey: 'Monkey',
  peacock: 'Peacock',
  cricket: 'Cricket',
  football: 'Football',
  badminton: 'Badminton',
  chess: 'Chess',
  samosa: 'Samosa',
  'pani-puri': 'Pani Puri',
  jalebi: 'Jalebi',
  'vada-pav': 'Vada Pav',
  'auto-rickshaw': 'Auto-rickshaw',
  bus: 'Bus',
  train: 'Train',
  bicycle: 'Bicycle',
  pencil: 'Pencil',
  eraser: 'Eraser',
  sharpener: 'Sharpener',
  ruler: 'Ruler',
  sun: 'Sun',
  moon: 'Moon',
  star: 'Star',
  rainbow: 'Rainbow',
  tabla: 'Tabla',
  guitar: 'Guitar',
  flute: 'Flute',
  trumpet: 'Trumpet',
  kite: 'Kite',
  'spinning-top': 'Spinning Top',
  marbles: 'Marbles',
  'yo-yo': 'Yo-yo',
  fish: 'Fish',
  crab: 'Crab',
  octopus: 'Octopus',
  whale: 'Whale',
};
